### ISSUE TITLE
CSS imports are not processed when using the plugin

### ISSUE THREAD

**Issue by Stvad** [shoonia/parcel-transformer-css-to-string#6]
I have the following css file that I want to inline:

```css
@import 'npm:tippy.js/dist/tippy.css';
@import 'npm:tippy.js/themes/light.css';

.iframe-preview,
.wikipedia-preview {
	width: 600px;
	height: 500px;
	border: none;
	padding: 0.4em 2px 2px;
}
...
```

When processed by the plugin it becomes the following string:
```js
exports.default = "@import 'npm:tippy.js/dist/tippy.css';\n@import 'npm:tippy.js/themes/light.css';\n\n.iframe-preview,\n.wikipedia-preview {\n\twidth: 600px;\n\theight: 500px;\n\tborder: none;\n\tpadding: 0.4em 2px 2px;\n}\n\n.tippy-content {\n\tpadding: 0;\n}\n\n.text-fragment-preview {\n\tpadding: 1px 0.5em;\n}\n";
```

**Expected behavior:** Imports are processed and the results are also inlined
